version: "3.9"

services:
    # php
    app:
        image: 'app3'
        container_name: app3
        build:
            context: .
            dockerfile: ./php/Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - ./src:/var/www/web
        working_dir: /var/www/web
        networks:
            - app-network

    # web server
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/web
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - db
        networks:
            - app-network

    # database
    db:
        container_name: mariadb
        image: mariadb:10.8.3
        ports:
            - "3306:3306"
        volumes:
            - ./data/mariadb:/var/lib/mysql
        environment:
            MYSQL_DATABASE: test_db
            MYSQL_USER: test_user
            MYSQL_PASSWORD: test_pass
            MYSQL_ROOT_PASSWORD: root_pass
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - app-network

    npm:
        image: node:lts-alpine
        container_name: npm
        volumes:
            - ./src:/var/www/web
        ports:
            - "3000:3000"
            - "3001:3001"
        working_dir: /var/www/web
        entrypoint: [ 'npm' ]
        networks:
            - app-network

    mailhog:
        image: mailhog/mailhog:latest
        container_name: mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - app-network

    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ./src:/var/www/web
        working_dir: /var/www/web
        entrypoint: [ 'composer', '--ignore-platform-reqs' ]
        networks:
            - app-network

    rabbitmq:
        image: rabbitmq:3.10.2-management-alpine
        container_name: rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: ruser
            RABBITMQ_DEFAULT_PASS: rpass
            RABBITMQ_DEFAULT_VHOST: /
        ports:
            - "15672:15672"
            - "5672:5672"
        networks:
            - app-network

# docker networks
networks:
    app-network:
        driver: bridge
